import type { SourceDef } from './src/types.js';

// 수집 대상 소스 선언 — 소스를 추가/제거하려면 이 파일만 수정하면 된다.
// Google Alerts는 https://www.google.com/alerts 에서 키워드 등록 후
// "RSS 피드로 전송"을 선택하고 생성된 피드 URL을 rss 타입으로 추가한다.
export const SOURCES: SourceDef[] = [
  // ── IT ──────────────────────────────────────────────
  {
    id: 'geeknews',
    name: 'GeekNews',
    type: 'rss',
    category: 'IT',
    target: 'https://feeds.feedburner.com/geeknews-feed',
    lang: 'ko',
  },
  {
    id: 'hackernews',
    name: 'Hacker News',
    type: 'hackernews',
    category: 'IT',
    target: '',
    limit: 20,
    lang: 'en',
  },

  // ── AI ──────────────────────────────────────────────
  {
    id: 'techcrunch-ai',
    name: 'TechCrunch AI',
    type: 'rss',
    category: 'AI',
    target: 'https://techcrunch.com/category/artificial-intelligence/feed/',
    lang: 'en',
  },
  {
    id: 'verge-ai',
    name: 'The Verge AI',
    type: 'rss',
    category: 'AI',
    target: 'https://www.theverge.com/rss/ai-artificial-intelligence/index.xml',
    lang: 'en',
  },
  {
    id: 'reddit-localllama',
    name: 'r/LocalLLaMA',
    type: 'reddit',
    category: 'AI',
    target: 'LocalLLaMA',
    lang: 'en',
  },

  // ── 글로벌 핫이슈 ────────────────────────────────────
  {
    id: 'bbc-world',
    name: 'BBC World',
    type: 'rss',
    category: '글로벌 핫이슈',
    target: 'https://feeds.bbci.co.uk/news/world/rss.xml',
    lang: 'en',
  },
  {
    id: 'reddit-worldnews',
    name: 'r/worldnews',
    type: 'reddit',
    category: '글로벌 핫이슈',
    target: 'worldnews',
    lang: 'en',
  },

  // ── 게임 ────────────────────────────────────────────
  {
    id: 'gamespot-news',
    name: 'GameSpot',
    type: 'rss',
    category: '게임',
    target: 'https://www.gamespot.com/feeds/game-news/',
    lang: 'en',
  },
  {
    id: 'gamedeveloper',
    name: 'Game Developer',
    type: 'rss',
    category: '게임',
    target: 'https://www.gamedeveloper.com/rss.xml',
    lang: 'en',
  },
  {
    id: 'inven',
    name: '인벤',
    type: 'rss',
    category: '게임',
    target: 'http://feeds.feedburner.com/inven',
    lang: 'ko',
  },
  {
    id: 'gamemeca',
    name: '게임메카',
    type: 'rss',
    category: '게임',
    target: 'https://www.gamemeca.com/rss.php',
    lang: 'ko',
  },
  {
    id: 'reddit-games',
    name: 'r/Games',
    type: 'reddit',
    category: '게임',
    target: 'Games',
    lang: 'en',
  },

  // ── 인사이트 ────────────────────────────────────────
  {
    id: 'medium-product',
    name: 'Medium #product-management',
    type: 'rss',
    category: '인사이트',
    target: 'https://medium.com/feed/tag/product-management',
    lang: 'en',
  },
  {
    id: 'aeon',
    name: 'Aeon',
    type: 'rss',
    category: '인사이트',
    target: 'https://aeon.co/feed.rss',
    lang: 'en',
  },
  {
    id: 'farnam-street',
    name: 'Farnam Street',
    type: 'rss',
    category: '인사이트',
    target: 'https://fs.blog/feed/',
    lang: 'en',
  },
  {
    id: 'bigthink',
    name: 'Big Think',
    type: 'rss',
    category: '인사이트',
    target: 'https://bigthink.com/feed/',
    lang: 'en',
  },

  // ── 아트 ────────────────────────────────────────────
  {
    id: 'colossal',
    name: 'Colossal',
    type: 'rss',
    category: '아트',
    target: 'https://www.thisiscolossal.com/feed/',
    lang: 'en',
  },
  {
    id: 'hyperallergic',
    name: 'Hyperallergic',
    type: 'rss',
    category: '아트',
    target: 'https://hyperallergic.com/feed/',
    lang: 'en',
  },
  {
    id: 'artnews',
    name: 'ARTnews',
    type: 'rss',
    category: '아트',
    target: 'https://www.artnews.com/feed/',
    lang: 'en',
  },
  {
    id: 'creative-boom',
    name: 'Creative Boom',
    type: 'rss',
    category: '아트',
    target: 'https://www.creativeboom.com/feed/',
    lang: 'en',
  },
  {
    id: 'artstation-mag',
    name: 'ArtStation Magazine',
    type: 'rss',
    category: '아트',
    target: 'https://magazine.artstation.com/feed/',
    lang: 'en',
  },
  {
    id: 'reddit-digitalart',
    name: 'r/DigitalArt',
    type: 'reddit',
    category: '아트',
    target: 'DigitalArt',
    lang: 'en',
  },

  // ── 증권 / 여행 / 맛집 (네이버 뉴스 검색 — 자격증명 없으면 자동 건너뜀) ──
  {
    id: 'naver-stock',
    name: '네이버뉴스 증시',
    type: 'navernews',
    category: '증권',
    target: '증시 전망',
    lang: 'ko',
  },
  {
    id: 'naver-travel',
    name: '네이버뉴스 여행',
    type: 'navernews',
    category: '여행',
    target: '여행 추천',
    lang: 'ko',
  },
  {
    id: 'atlas-obscura',
    name: 'Atlas Obscura',
    type: 'rss',
    category: '여행',
    target: 'https://www.atlasobscura.com/feeds/latest',
    lang: 'en',
  },
  {
    id: 'travie',
    name: '트래비 매거진',
    type: 'rss',
    category: '여행',
    target: 'https://www.travie.com/rss/allArticle.xml',
    lang: 'ko',
  },

  // ── 맛집 (특화 키워드 + 유튜브 채널) ──
  {
    id: 'naver-food-omakase',
    name: '네이버뉴스 오마카세',
    type: 'navernews',
    category: '맛집',
    target: '오마카세 맛집',
    lang: 'ko',
  },
  {
    id: 'naver-food-nopo',
    name: '네이버뉴스 노포',
    type: 'navernews',
    category: '맛집',
    target: '노포 맛집',
    lang: 'ko',
  },
  {
    id: 'yt-sungsikyung',
    name: '성시경 (먹을텐데)',
    type: 'rss',
    category: '맛집',
    target: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCl23-Cci_SMqyGXE1T_LYUg',
    limit: 10,
    lang: 'ko',
  },
  {
    id: 'yt-meatcreator',
    name: '정육왕',
    type: 'rss',
    category: '맛집',
    target: 'https://www.youtube.com/feeds/videos.xml?channel_id=UC1oXmhvYHVI2bApphh3IzuQ',
    limit: 10,
    lang: 'ko',
  },
];
